import Head from 'next/head'
import Link from'next/link'
import styles from '../styles/Home.module.css'

export default function Home({author}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Site legal do Petterson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sobre o sistema
        </h1>

        O sistema foi feito em live para demonstrar os primeiros passos com o framewok Next.js
        <hr />
        Autor: {author}

        <Link href="/busca">Ir para a Busca</Link>


      </main>
    </div>
  )
}

export async function getStaticProps(){
  
  return {
    props:{
      author: 'Petterson Galdino'
    }
  };
}