import Head from 'next/head'
import Link from'next/link'
import styles from '../styles/Home.module.css'

export default function Home({author}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Site legal do Petterson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.menu}>
          <Link href="/">Início</Link>
          <Link href="/busca">Busca</Link>
        </div>
        <h1 className={styles.title}>
          Sobre
        </h1>
        Projeto realizado com o framework Next.js sendo uma parte do segundo exercicio sobre Server-side rendering da disciplina de Arquitetura de Front Ends do curso de
        Pós graduação em Engenharia de Software.
        <h3> Professor: Samuel Martins</h3>
        <h3> Autores: {author}</h3>
      </main>
    </div>
  )
}

export async function getStaticProps(){
  
  return {
    props:{
      author: 'Petterson Galdino e Rafael Albuquerque Basto da Costa'
    }
  };
}